name: Deploy StudyFlow

on:
  push:
    branches:
      - main   # deploy on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to VPS via SSH
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        VPS_PORT: ${{ secrets.VPS_PORT }}
      run: |
        echo "Deploying StudyFlow..."
        sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no "$VPS_USER@$VPS_HOST" -p "$VPS_PORT" << 'EOF'
          cd /home/jamil/StudyFlow

          # Pull latest code
          git fetch origin main
          git reset --hard origin/main

          # Activate virtualenv
          source venv/bin/activate

          # Install dependencies
          pip install -r requirements.txt

          # Apply migrations
          python manage.py migrate

          # Collect static files
          python manage.py collectstatic --noinput

          # Start or reload Gunicorn with PM2 using Python interpreter
          if pm2 list | grep -q studyflow; then
              echo "Reloading StudyFlow with PM2..."
              pm2 reload studyflow
          else
              echo "Starting StudyFlow with PM2..."
              pm2 start /home/jamil/StudyFlow/venv/bin/gunicorn \
                  --name studyflow \
                  --interpreter python3 \
                  -- core.wsgi:application --bind 127.0.0.1:8001
              pm2 save
              pm2 startup
          fi

          echo "Deployment complete!"
        EOF
