# Generated by Django 5.2.5 on 2025-09-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classrooms.classroom'),
        ),
    ]
