# Generated by Django 5.2.5 on 2025-09-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
