# Generated by Django 5.2.5 on 2025-09-05 03:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_memberships_role_alter_memberships_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memberships',
            new_name='Membership',
        ),
    ]
