# Generated by Django 5.2.5 on 2025-09-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('classrooms', '0001_initial'),
        ('organizations', '0003_rename_memberships_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
        migrations.AddField(
            model_name='membership',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='classrooms.classroom'),
        ),
    ]
