# Generated by Django 5.2.5 on 2025-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_assignment_assignmentsubmission_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
