# Generated by Django 5.2.5 on 2025-09-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
